# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Note API Test

on:
  push:
    branches: [ "api/dev" ]
  pull_request:
    branches: [ "api/main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: get secrets
        uses: actions/checkout@v3
        with:
          repository: hrabit64/Springnote-secret
          ref: main
          path: "./src/main/resources"
          token: ${{ secrets.TOKEN }}

      - name: get test resources
        uses: actions/checkout@v3
        with:
          repository: hrabit64/Springnote-secret
          ref: test
          path: "./src/test/resources"
          token: ${{ secrets.TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test with Gradle
        continue-on-error: true
        run: ./gradlew test

      - name: Archive build reports
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: ./build/reports/tests/test
