name: Spring Note API Test

on:
  push:
    branches:
      - '**/dev'

permissions:
  contents: read

jobs:
  run-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: setup tmp dir
        run: mkdir -p tmp

      - name: get secrets
        uses: actions/checkout@v3
        with:
          repository: hrabit64/Springnote-secret
          ref: main
          path: "./tmp"
          token: ${{ secrets.TOKEN }}

      - name: move secrets
        run: mv ./tmp/* src/main/resources/

      - name: get test resources
        uses: actions/checkout@v3
        with:
          repository: hrabit64/Springnote-secret
          ref: test
          path: "./tmp"
          token: ${{ secrets.TOKEN }}

      - name: create test resources
        run: mkdir -p src/test/resources/

      - name: move test resources
        run: mv ./tmp/* src/test/resources/

      - name: remove tmp dir
        run: rm -rf tmp

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test with Gradle
        continue-on-error: true
        id: test
        run: ./gradlew test

      - name: Archive build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-report
          path: ./build/reports/tests/test

      - name: Fail if tests failed
        if: ${{ steps.test.outcome == 'failure' }}
        run: exit 1
